version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbPassword
      MYSQL_DATABASE: edutrackerdb
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: dbPassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/edutrackerdb
      SPRING_DATASOURCE_USERNAME: dbUser
      SPRING_DATASOURCE_PASSWORD: dbPassword


  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mysql_data:


